"""What produced a result, stamped into the result.

Twice in one phase a bug invalidated a set of numbers, and both times the expensive part
was not fixing it — it was working out which artifacts on disk had inherited it. The
answer came from reading commit timestamps against file mtimes, which is archaeology,
and archaeology is what you do when the record is missing.

So every report carries this. Afterwards the question "which results are invalid" is a
query rather than an investigation:

    results whose `scorer` predates abc123 used the uncollapsed merge

**`version` is the one that matters and it is bumped by hand.** A commit hash says the
code differed; it does not say whether the difference *meant* anything. `EVALUATION`
changes only when the meaning of a number changes — a metric redefined, a bug that
alters published figures, a scorer that starts counting something else. Two runs sharing
a version are comparable; two runs that differ are not, whatever their commits say.
Automating it would defeat it, because a machine cannot tell a typo fix from a
redefinition.

**A dirty tree is recorded, not refused.** Refusing would block the exploratory runs that
are most of the work. But a stamp whose commit does not identify the code is worth
knowing about, so `dirty` travels with it and the renderer says so.

**The corpus is fingerprinted, because it moves too.** `report.json` overstated
end-to-end field accuracy by three and a half points for weeks, purely because the corpus
was rebuilt underneath it and nobody re-scored. A commit hash would not have caught that:
the code was correct, the labels had changed. Hashing the label files does catch it.
"""
from __future__ import annotations

import hashlib
import os
import subprocess

# Bumped by hand when the meaning of a number changes. History, newest first:
#
#   phase6-v2   repair.cli._merge now collapses optional fields. Before this, every
#               repaired record kept the {"status":..., "value":...} shape for optional
#               fields, and the scorer read it as a fabricated value. Any repair result
#               stamped earlier -- or unstamped -- overstates damage and understates net
#               delta. It moved the degraded guided arm from -0.029 to +0.002.
#   phase6-v1   first repair scorer.
EVALUATION = "phase6-v2"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _git(*args):
    try:
        out = subprocess.run(("git",) + args, cwd=ROOT, capture_output=True,
                             text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return ""
    return out.stdout.strip() if out.returncode == 0 else ""


def corpus_fingerprint(corpus_root: str) -> dict:
    """A hash of the label files, which are what "correct" means.

    Only the labels, not the documents. The PDFs can be regenerated byte-differently
    from the same seed without changing a single answer, and hashing them would report
    a corpus change on every rebuild. The labels changing is what makes an old score
    incomparable.
    """
    labels = os.path.join(corpus_root, "labels")
    if not os.path.isdir(labels):
        return {"corpus": corpus_root, "labels": None}
    digest = hashlib.sha256()
    names = sorted(n for n in os.listdir(labels) if n.endswith(".json"))
    total = 0
    for name in names:
        path = os.path.join(labels, name)
        with open(path, "rb") as handle:
            payload = handle.read()
        digest.update(name.encode("utf-8"))
        digest.update(payload)
        total += len(payload)
    return {
        "corpus": corpus_root,
        "label_files": len(names),
        "label_bytes": total,
        "labels": digest.hexdigest()[:16],
    }


def stamp(corpus_root: str = "", extra: dict = None) -> dict:
    """Everything needed to decide later whether a result is still comparable."""
    commit = _git("rev-parse", "HEAD")
    dirty = bool(_git("status", "--porcelain"))
    out = {
        "evaluation_version": EVALUATION,
        "commit": commit[:12] or None,
        # True means the commit does not identify the code that ran. Not an error --
        # most exploratory runs are dirty -- but not something to discover later.
        "dirty": dirty,
        "branch": _git("rev-parse", "--abbrev-ref", "HEAD") or None,
    }
    if corpus_root:
        out.update(corpus_fingerprint(corpus_root))
    if extra:
        out.update(extra)
    return out


def describe(stamped: dict) -> str:
    """One line, for a report header."""
    if not stamped:
        return "unstamped -- provenance unknown, treat as incomparable"
    bits = [f"eval {stamped.get('evaluation_version', '?')}",
            f"commit {stamped.get('commit') or '?'}"]
    if stamped.get("dirty"):
        bits.append("DIRTY (commit does not identify the code)")
    if stamped.get("labels"):
        bits.append(f"labels {stamped['labels']}")
    return " · ".join(bits)


def comparable(one: dict, two: dict) -> tuple:
    """Can these two results be put in the same table? Returns (bool, why-not).

    Deliberately strict on the evaluation version and on the labels, and silent about
    the commit. A commit difference is usually a comment or a renderer tweak; a version
    difference is a statement that a number changed meaning, and a label difference
    means the two were scored against different notions of correct.
    """
    if not one or not two:
        return False, "one of them is unstamped"
    if one.get("evaluation_version") != two.get("evaluation_version"):
        return False, (f"evaluation {one.get('evaluation_version')} against "
                       f"{two.get('evaluation_version')} -- a number changed meaning "
                       f"between them")
    if one.get("labels") != two.get("labels"):
        return False, "scored against different corpus labels"
    return True, ""
